### ISSUE TITLE
Reference dataset

### ISSUE THREAD

**Issue by arnavyayavaram** [facebookresearch/DIG-In#1]
https://github.com/facebookresearch/DIG-In/blob/ce46b28f0fa3b926deddb60be98ce477556f8108/compute_metrics.py#L92

It is not clear where the file mentioned at this line is created. There is also a mismatch between the prompts in the csv files and the original Geode dataset.
Overall it is not clear how and where the reference dataset comes into play from the code and the TODO's do not help clarify this. Please let me know how to address this.  Thank you!

**Comment by melissah14** [comment]
[[Handled over email but commenting here for posterity]]

For context, `geode_all_inceptionv3.pkl` is used as the real, reference image features that become the reference manifold against which generated images are compared. 

> It is not clear where the file mentioned at this line is created. 

You can create this file by adapting `get_features_inceptionv3.py` and passing in the dataset of real GeoDE images. For this, you will need to pass in paths to the "prompt" csv and GeoDE image folder. You may have to make a few edits to the input csv and get_features script to confirm that it points correctly to your GeoDE images. 

> There is also a mismatch between the prompts in the csv files and the original Geode dataset.

Yes, we removed images from GeoDE that contain the tree tag, i.e. filtering with `geode_df[geode_df['tree_tag']=='no']`. The reason for doing so is we wanted to avoid any spurious correlations with trees in our measurements. I will update the README to denote this.

> Overall it is not clear how and where the reference dataset comes into play from the code and the TODO's do not help clarify this.

This reference dataset is analogous to the generated dataset, with extracted features pertaining to each image in the GeoDE dataset. There should be a 1:1 mapping between your real and generated images (and features). Then, the precision/recall/density/coverage metrics are calculated by comparing the manifold of real GeoDE images features to the manifold of  generated image features.
